### ISSUE TITLE
Array of structs doesn't work

### ISSUE THREAD

**Issue by davispuh** [dryrb/dry-types#22]
I thought this should work, but it doesn't...

```ruby
require 'dry-data'

module Types
end

Dry::Data.configure do |config|
  config.namespace = Types
end

Dry::Data.finalize

class Book < Dry::Data::Value
  attribute :name,      Types::Maybe::Strict::String
end

class Shelf < Dry::Data::Value
  attribute :books,     Types::Strict::Array.member(Book)
end

book1 = Book.new(:name => 'A book name')
book2 = Book.new(:name => 'Another book')

puts Shelf.new(:books => [book1, book2]).inspect
```

```
Dry::Data::StructError: [Shelf.new] [#<Book name=Some("A book name")>, #<Book name=Some("Another book")>] (Array) has invalid type for :books
        from /usr/lib/ruby/gems/2.3.0/gems/dry-data-0.5.1/lib/dry/data/struct.rb:36:in `rescue in new'
        from /usr/lib/ruby/gems/2.3.0/gems/dry-data-0.5.1/lib/dry/data/struct.rb:34:in `new'
```

**Comment by davispuh** [comment]
this doesn't work too

```ruby

class Shelf < Dry::Data::Value
  attribute :books,     Types::Strict::Array.member(Types::Maybe::Strict::String)
end

class Room < Dry::Data::Value
  attribute :shelf, Shelf
end

shelf = Shelf.new(:books => ['Some book'])

puts Room.new(:shelf => shelf).inspect
```

```
/usr/lib/ruby/gems/2.3.0/gems/dry-data-0.5.1/lib/dry/data/struct.rb:36:in `rescue in new': [Room.new] #<Shelf books=[Some("Some book")]> (Shelf) has invalid type for :shelf (Dry::Data::StructError)
        from /usr/lib/ruby/gems/2.3.0/gems/dry-data-0.5.1/lib/dry/data/struct.rb:34:in `new'
```

**Comment by solnic** [comment]
Thanks for the report. I'll fix it in the next release.

**Comment by marshall-lee** [comment]
@solnic more generic problem:
```ruby
class X
end
Dry::Types.register_class(X)
Dry::Types[X][X.new] # ArgumentError: wrong number of arguments (given 1, expected 0)
```

This:
```ruby
class Y < Dry::Types::Struct
  attribute :y, Types::Strict::String
end
type = Dry::Types[Y]

attributes = { y: '---' }
y = Y.new(attributes) # => #<Y:0x00000004ed0d88 @y="---">
type[attributes] # => #<Y:0x00000004d265c8 @y="---">
type[y] # => #<Y:0x00000004f0bd48 @y="---">
```
Works just by occasion, because `y` responds to `[]` just like `attributes`.

I think that `Dry::Types[Y]` should not recreate instances that are already valid. If your upcoming refactoring solves this issue it would be good.

**Comment by solnic** [comment]
@marshall-lee it doesn't recreate, or at least it should not. defo a bug, will fix
